FROM alpine:latest as build

RUN apk --no-cache add curl tar gzip

#
# Install JDK
#
RUN curl https://cdn.azul.com/zulu/bin/zulu11.2.3-jdk11.0.1-linux_musl_x64.tar.gz -o /jdk.tar.gz
RUN mkdir -p /opt/jdk
RUN tar xzf /jdk.tar.gz --strip-components=1 -C /opt/jdk
ENV PATH=/opt/jdk/bin:$PATH
ENV JAVA_HOME=/opt/jdk

#
# Build LDS Server
#
RUN ["jlink", "--strip-debug", "--no-header-files", "--no-man-pages", "--compress=2", "--module-path", "/opt/jdk/jmods", "--output", "/linked",\
 "--add-modules", "jdk.unsupported,java.base,java.management,java.net.http,java.xml,java.naming,java.sql,java.desktop,java.sql"]

#
# Build LDS image
#
FROM alpine:latest

#
# Resources from build image
#
COPY --from=build /linked /opt/jdk/
COPY target/dependency /opt/lds/lib/
COPY target/linked-data-store-*.jar /opt/lds/server/
RUN touch /opt/lds/saga.log

ENV PATH=/opt/jdk/bin:$PATH

WORKDIR /opt/lds

VOLUME ["/conf", "/schemas"]

EXPOSE 9090

CMD ["java", "-cp", "/opt/lds/server/*:/opt/lds/lib/*", "no.ssb.lds.server.Server"]
