version: '3.3'

services:

  lds-postgres:
    image: lds-postgres:dev
    ports:
    - "9090:9090"
    volumes:
    - conf:/conf:ro
    - schemas:/schemas:ro
    depends_on:
    - postgresdb

  postgresdb:
    build:
      context: .
      dockerfile: Dockerfile-Postgres
    image: db-postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
    - 8080:8080

volumes:
  pgdata:
  conf:
    driver: local
    driver_opts:
      type: none
      device: ${CONF_FOLDER}
      o: bind
  schemas:
    driver: local
    driver_opts:
      type: none
      device: ${SCHEMA_FOLDER}
      o: bind
